<Project Sdk="Microsoft.NET.Sdk.Worker">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/OpenFlow.Domain/OpenFlow.Domain.csproj" />
    <ProjectReference Include="../../src/OpenFlow.Application/OpenFlow.Application.csproj" />
    <ProjectReference Include="../../src/OpenFlow.Infrastructure/OpenFlow.Infrastructure.csproj" />
    <ProjectReference Include="../../src/OpenFlow.Contracts/OpenFlow.Contracts.csproj" />
  </ItemGroup>
</Project>