<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../OpenFlow.Domain/OpenFlow.Domain.csproj" />
    <ProjectReference Include="../OpenFlow.Contracts/OpenFlow.Contracts.csproj" />
  </ItemGroup>
</Project>